name: Deploy to EC2 (main)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PORT: ${{ secrets.EC2_SSH_PORT || '22' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            set -e
            echo "===== Deploy start: $(date) ====="

            # Remove old folder and clone fresh
            if [ -d "/home/ubuntu/resume_builder_back" ]; then
              rm -rf /home/ubuntu/resume_builder_back
            fi
            git clone git@github.com:huzaifa-khambaty/resume_builder_back.git /home/ubuntu/resume_builder_back

            cd /home/ubuntu/resume_builder_back

            # Install dependencies
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi

            # No build step required
            echo "Skipping build step (no build script in package.json)"

            # Start / restart with pm2
            pm2 restart resume_builder_back || pm2 start npm --name "resume_builder_back" -- start

            pm2 save
            echo "===== Deploy finished: $(date) ====="
