name: Deploy to EC2 (main)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PORT: ${{ secrets.EC2_SSH_PORT || '22' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            set -e
            echo "===== Deploy start: $(date) ====="

            cd /home/ubuntu/resume_builder_back

            # Update repo
            git fetch --all
            git reset --hard origin/main

            # Install dependencies
            npm install

            # Run migrations
            npm run migrate

            # Restart app with PM2
            pm2 restart resume_builder_back || pm2 start npm --name "resume_builder_back" -- start
            pm2 save

            echo "===== Deploy finished: $(date) ====="
